/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history-roll-call` | `/history-roll-call`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/roll-call` | `/roll-call`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/schedule/create` | `/schedule/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/schedule/edit` | `/schedule/edit`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/schedule` | `/schedule`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/status` | `/status`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/status/register` | `/status/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explain` | `/explain`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/history-roll-call` | `/history-roll-call`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/roll-call` | `/roll-call`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/schedule/create` | `/schedule/create`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/schedule/edit` | `/schedule/edit`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/schedule` | `/schedule`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/status` | `/status`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/status/register` | `/status/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explain` | `/explain`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/history-roll-call${`?${string}` | `#${string}` | ''}` | `/history-roll-call${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/roll-call${`?${string}` | `#${string}` | ''}` | `/roll-call${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/schedule/create${`?${string}` | `#${string}` | ''}` | `/schedule/create${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/schedule/edit${`?${string}` | `#${string}` | ''}` | `/schedule/edit${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/schedule${`?${string}` | `#${string}` | ''}` | `/schedule${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/status${`?${string}` | `#${string}` | ''}` | `/status${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/status/register${`?${string}` | `#${string}` | ''}` | `/status/register${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explain${`?${string}` | `#${string}` | ''}` | `/explain${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history-roll-call` | `/history-roll-call`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/roll-call` | `/roll-call`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/schedule/create` | `/schedule/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/schedule/edit` | `/schedule/edit`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/schedule` | `/schedule`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/status` | `/status`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/status/register` | `/status/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explain` | `/explain`; params?: Router.UnknownInputParams; };
    }
  }
}
